# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='DiceFighter_RetInfo.proto',
  package='cn.senss.server.message',
  serialized_pb='\n\x19\x44iceFighter_RetInfo.proto\x12\x17\x63n.senss.server.message\"*\n\x07RetInfo\x12\r\n\x05\x65rror\x18\x01 \x02(\r\x12\x10\n\x08\x65rrorStr\x18\x02 \x02(\t')




_RETINFO = descriptor.Descriptor(
  name='RetInfo',
  full_name='cn.senss.server.message.RetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='cn.senss.server.message.RetInfo.error', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorStr', full_name='cn.senss.server.message.RetInfo.errorStr', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['RetInfo'] = _RETINFO

class RetInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RETINFO
  
  # @@protoc_insertion_point(class_scope:cn.senss.server.message.RetInfo)

# @@protoc_insertion_point(module_scope)
