# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='DiceFighter_LoginRequest.proto',
  package='cn.senss.server.message',
  serialized_pb='\n\x1e\x44iceFighter_LoginRequest.proto\x12\x17\x63n.senss.server.message\",\n\x0cLoginRequest\x12\x0b\n\x03uin\x18\x01 \x02(\r\x12\x0f\n\x07role_id\x18\x02 \x02(\r')




_LOGINREQUEST = descriptor.Descriptor(
  name='LoginRequest',
  full_name='cn.senss.server.message.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uin', full_name='cn.senss.server.message.LoginRequest.uin', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='role_id', full_name='cn.senss.server.message.LoginRequest.role_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST

class LoginRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINREQUEST
  
  # @@protoc_insertion_point(class_scope:cn.senss.server.message.LoginRequest)

# @@protoc_insertion_point(module_scope)
